name: Terraform Destroy

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
      TF_VERSION: 1.2.3 # specify your Terraform version

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: examples/asg
        run: terraform init -backend-config="bucket=${{ env.S3_BUCKET }}" -backend-config="key=examples/asg/terraform.tfstate"

      - name: Terraform Plan for Destroy
        working-directory: examples/kms
        run: terraform plan -destroy -out=tfplan

      - name: Terraform Destroy
        working-directory: examples/kms
        run: terraform apply -auto-approve tfplan