name: Terraform Plan & Apply

on:
  push:
    branches:
      - main
    paths:
      - 'examples/kms/**'
  pull_request:
    branches:
      - main
    paths:
      - 'examples/kms/**'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
      TF_VERSION: 1.2.3 # specify your Terraform version
      TFLINT_VERSION: 0.34.1 # specify your TFLint version

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install TFLint
        run: |
          curl -sL "https://github.com/terraform-linters/tflint/releases/download/v${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip" -o tflint.zip
          unzip tflint.zip -d /usr/local/bin/
          tflint --version

      - name: Terraform Init
        working-directory: examples/kms
        run: terraform init -backend-config="bucket=${{ env.S3_BUCKET }}" -backend-config="key=examples/kms/terraform.tfstate"

      - name: Terraform Format
        working-directory: examples/kms
        run: terraform fmt

      - name: TFLint
        working-directory: examples/kms
        run: |
          tflint --init
          tflint .

      - name: Terraform Plan
        working-directory: examples/kms
        run: terraform plan -out=tfplan

      - name: Save Plan Output
        working-directory: examples/kms
        run: terraform show -json tfplan > tfplan.json

      - name: Upload Plan for Approval
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: examples/kms/tfplan.json

  apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform
    environment: Terraform Apply

    steps:
      - name: Download Plan
        uses: actions/download-artifact@v2
        with:
          name: tfplan

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: examples/kms
        run: terraform init -backend-config="bucket=${{ secrets.S3_BUCKET_NAME }}" -backend-config="key=examples/kms/terraform.tfstate"

      - name: Terraform Apply
        working-directory: examples/kms
        run: terraform apply -auto-approve tfplan.json    