name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'examples/kms/**'
  pull_request:
    branches:
      - main
    paths:
      - 'examples/kms/**'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
      TF_VERSION: 1.2.3 # specify your Terraform version
      TFLINT_VERSION: 0.34.1 # specify your TFLint version

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install TFLint
        run: |
          curl -sL "https://github.com/terraform-linters/tflint/releases/download/v${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip" -o tflint.zip
          unzip tflint.zip -d /usr/local/bin/
          tflint --version

      - name: Terraform Init
        working-directory: examples/kms
        run: terraform init -backend-config="bucket=${{ env.S3_BUCKET }}" -backend-config="key=examples/kms/terraform.tfstate"

      - name: Terraform Format
        working-directory: examples/kms
        run: terraform fmt

      - name: TFLint
        working-directory: examples/kms
        run: |
          tflint --init
          tflint .

      - name: Terraform Plan
        working-directory: examples/kms
        run: terraform plan -out=tfplan

      - name: Request Approval
        if: github.event_name == 'pull_request'
        id: approval_step
        run: echo "Awaiting approval to proceed with Terraform Apply."
        timeout-minutes: 10 # Adjust the timeout as needed

      - name: Terraform Apply
        working-directory: examples/kms
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
        run: terraform apply -auto-approve tfplan